name: studywithme
description: wblearn,studywithme,study video.
keyword: "wblearn, @wblearn,studywithme,study video,studyaccount, study with me, 个人网站, 互联网"
url: 'https://wblearn.github.io/study-video/'
baseurl: '/studywithme'
email: 1275660493@qq.com
weibo: https://weibo.com/5717080324
twitter: https://twitter.com/wblearn1
youtube: https://www.youtube.com/wblearn713
google_analytics: 'UA-00000000-1'

# LiveRe setttings
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC8zODIwNi8xNDczNA==

################################################################
################################################################
encoding: utf-8
gems:
  - jekyll-sitemap
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
collections:
  videos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
  -
    scope:
      path: ''
      type: videos
    values:
      layout: video